version: '3'

services:
  pigeon_app:
    container_name: pigeon_app
    build: .
    ports:
      - 8000:8000
    volumes:
      - ./.env:/pigeon/.env
      - ./secrets/app/${ENVIRONMENT}:/pigeon/secrets
      - ./app:/pigeon/app

  mongodb:
    container_name: mongo_db
    image: mongo:6.0
    ports:
      - 27017:27017
    volumes:
      - ./data:/pigeon/data
      - ./secrets/mongodb/${ENVIRONMENT}:/pigeon/secrets/
    environment:
      - MONGO_INITDB_ROOT_USERNAME_FILE=/pigeon/secrets/mongodb_username.txt
      - MONGO_INITDB_ROOT_PASSWORD_FILE=/pigeon/secrets/mongodb_password.txt
