version: '3'

services:
  pigeon_app:
    container_name: pigeon_app
    build: .
    ports:
      - 8000:8000
    volumes:
      - ./.env:/pigeon/.env
      - ./secrets/${ENVIRONMENT}:/pigeon/secrets
      - ./app:/pigeon/app

  mongodb:
    container_name: ${DB_CONTAINER_NAME}
    image: mongo:6.0
    restart: always
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - ./secrets/${ENVIRONMENT}/mongodb:/pigeon/secrets/
      - ./mongodb/data/db:/data/db
      - ./mongodb/init_scripts:/docker-entrypoint-initdb.d
    environment:
      - MONGO_INITDB_ROOT_USERNAME_FILE=/pigeon/secrets/mongodb_username.txt
      - MONGO_INITDB_ROOT_PASSWORD_FILE=/pigeon/secrets/mongodb_password.txt
      - MONGO_INITDB_DATABASE=${DB_NAME}
      - MONGOSH=mongosh --username "$(cat $$MONGO_INITDB_ROOT_USERNAME_FILE)" --password "$(cat $$MONGO_INITDB_ROOT_PASSWORD_FILE)" --authenticationDatabase admin $$MONGO_INITDB_DATABASE
